# fly.toml app configuration file generated for youtube-video-engine
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "youtube-video-engine"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  FLASK_ENV = "production"
  LOG_LEVEL = "INFO"
  GUNICORN_LOG_LEVEL = "info"
  WEBHOOK_BASE_URL = "https://youtube-video-engine.fly.dev"

[processes]
  app = "gunicorn --config gunicorn.conf.py app:app"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 40

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    restart_limit = 0

  [[services.http_checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "10s"
    method = "get"
    path = "/health/basic"
    protocol = "http"
    restart_limit = 0
    tls_skip_verify = false

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
